version: '3.0'

services:
  api:
    image: samtecspg/articulate-api:0.22.0
    ports: ['7500:7500']
  ui:
    image: samtecspg/articulate-ui:0.22.0
    ports: ['3000:3000']
  rasa:
    image: samtecspg/articulate-rasa:0.22.0
    ports: ['5000:5000']
    volumes: ["${MODEL_DIR:-./local-storage/rasa/nlu-model}:/app/projects", "${RASA_CONFIG:-./local-storage/rasa/rasa-config.yml}:/app/config.yml", "./local-storage/rasa/logs:/app/logs"]
  duckling:
    image: samtecspg/duckling:0.1.6.0
    ports: ['8000:8000']
  redis:
    image: redis:4.0.6-alpine
    ports: ['6379:6379']
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA:-./local-storage/redis-data}:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_TAG:-6.5.1}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ['9200:9200']
    volumes:
      - ${ES_CONFIG:-./local-storage/elasticsearch/config/elasticsearch.yml}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_DATA:-./local-storage/elasticsearch/data}:/usr/share/elasticsearch/data
      - ${ES_DATA:-./local-storage/elasticsearch/docker-healthcheck.sh}:/usr/share/docker-healthcheck.sh
